version: '3.8'

services:
  backend:
    container_name: this-cord-backend
    restart: always
    build: ./backend
    ports:
      - "4000:4000"
  frontend:
    container_name: this-cord-frontend
    restart: always
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      - backend